[workspace]
resolver = "2"
members = ["reclaim-verify", "cliprail", "humanity"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
soroban-sdk = { version = "28", features = ["hazmat-crypto"] }
reclaim-verify = { path = "reclaim-verify" }
k256 = { version = "0.13", features = ["ecdsa"] }
sha3 = "0.10"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
