[package]
name = "cliprail"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
reclaim-verify = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
reclaim-verify = { workspace = true, features = ["testutils"] }
humanity = { path = "../humanity" }
